swagger: "2.0"
info:
  title: Events Api
  description: API for the Events App
  version: 1.0.0
host: gateway-events-api-ex7otr565q-uc.a.run.app
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://gateway-events-api-ex7otr565q-uc.a.run.app
  protocol: h2
paths:
  /events:
    get:
      description: Get all events
      operationId: getEvents
      responses:
        200:
          description: Success.
          schema:
            type: string
    post:
      description: Add an event
      operationId: addEvent
      responses:
        200:
          description: Success
          schema:
            type: string
  /events/{eventId}:
    get:
      description: Get event by ID
      operationId: getEventById
      parameters:
        - in: path
          name: eventId
          required: true
          type: string
          minimum: 1
      responses:
        200:
          description: Success
          schema:
            type: string
    put:
      description: Update event
      operationId: updateEvent
      parameters:
        - in: path
          name: eventId
          required: true
          type: string
          minimum: 1
      responses:
        200:
          description: Success
          schema:
            type: string
    delete:
      description: Delete event
      operationId: deleteEvent
      parameters:
        - in: path
          name: eventId
          required: true
          type: string
          minimum: 1
      responses:
        200:
          description: Success
          schema:
            type: string